### PR TITLE
ron-3: fixed the name bug

### LINKED ISSUE #3: User name input not reflected on the /hello page
After typing in the user name and click "Greet me", the name typed in is not reflected in the next pag.

### PR DESCRIPTION
**Pull request by RonZhang724**
in the hello() function,
change the request param name from `name` to `myName` to match the html form param name.

### CODE REVIEW

File: demo/src/main/java/com/example/demo/DemoApplication.java [hunk 1]
```diff
@@ -15,7 +15,7 @@ public static void main(String[] args) {
 	}
 
 	@GetMapping("/hello")
-	public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
```
Comment (RonZhang724) [inline demo/src/main/java/com/example/demo/DemoApplication.java:18]: We need to write tests for this. But we can do it in future MRs.
